### ISSUE TITLE
UnboundLocalError: local variable 'from_live' referenced before assignment

### ISSUE THREAD

**Issue by aadler** [eyeonus/Trade-Dangerous#12]
I downloaded a fresh copy of TD and was running a clean install when I got the following error:

```
F:\>cd elite/td

F:\Elite\TD>trade import -P eddblink -O clean
NOTE: Rebuilding cache file: this may take a few moments.
NOTE: Missing "F:\Elite\TD\data\TradeDangerous.prices" file - no price data.
NOTE: Downloading file 'modules.json'.
NOTE: Requesting http://elite.ripz.org/files/modules.json
NOTE: Downloaded 292.3KB of gziped data 510.5KB/s
NOTE: Processing Upgrades: Start time = 2018-06-25 19:56:17.902780
NOTE: Finished processing Upgrades. End time = 2018-06-25 19:56:17.913750
NOTE: Downloading file 'index.json'.
NOTE: Requesting https://raw.githubusercontent.com/EDCD/coriolis-data/master/dist/index.json
NOTE: Downloaded   0.7MB of gziped data  10.9MB/s
NOTE: Processing Ships: Start time = 2018-06-25 19:56:18.237884
NOTE: Finished processing Ships. End time = 2018-06-25 19:56:18.244865
NOTE: Downloading file 'systems_populated.jsonl'.
NOTE: Requesting http://elite.ripz.org/files/systems_populated.jsonl
NOTE: Downloaded  20.5MB of gziped data   1.1MB/s
NOTE: Processing Systems: Start time = 2018-06-25 19:56:37.701863
NOTE: Finished processing Systems. End time = 2018-06-25 19:56:38.979448
NOTE: Downloading file 'stations.jsonl'.
NOTE: Requesting http://elite.ripz.org/files/stations.jsonl
NOTE: Downloaded 113.5MB of gziped data   3.2MB/s
NOTE: Processing Stations, this may take a bit: Start time = 2018-06-25 19:57:15.028101
NOTE: Simultaneously processing ShipVendors.
NOTE: Simultaneously processing UpgradeVendors, this will take quite a while.
NOTE: Finished processing Stations. End time = 2018-06-25 20:01:56.025085
NOTE: Downloading file 'commodities.json'.
NOTE: Requesting http://elite.ripz.org/files/commodities.json
NOTE: Downloaded  99.3KB of gziped data 213.7KB/s
NOTE: Processing Categories and Items: Start time = 2018-06-25 20:01:57.189972
NOTE: Finished processing Categories and Items. End time = 2018-06-25 20:01:57.194958
NOTE: F:\Elite\TD\data\Category.csv exported.
NOTE: F:\Elite\TD\data\Item.csv exported.
NOTE: F:\Elite\TD\data\Ship.csv exported.
NOTE: F:\Elite\TD\data\ShipVendor.csv exported.
NOTE: F:\Elite\TD\data\Station.csv exported.
NOTE: F:\Elite\TD\data\System.csv exported.
NOTE: F:\Elite\TD\data\Upgrade.csv exported.
NOTE: F:\Elite\TD\data\UpgradeVendor.csv exported.
NOTE: Downloading file 'listings.csv'.
NOTE: Requesting http://elite.ripz.org/files/listings.csv
NOTE: Downloaded 149.2MB of gziped data   4.0MB/s
NOTE: Processing market data from listings.csv: Start time = 2018-06-25 20:04:05.625704
Traceback (most recent call last):
  File "F:\Elite\TD\trade.py", line 104, in <module>
    main(sys.argv)
  File "F:\Elite\TD\trade.py", line 77, in main
    results = cmdenv.run(tdb)
  File "F:\Elite\TD\commands\commandenv.py", line 81, in run
    return self._cmd.run(results, self, tdb)
  File "F:\Elite\TD\commands\import_cmd.py", line 124, in run
    if not plugin.run():
  File "F:\Elite\TD\plugins\eddblink_plug.py", line 814, in run
    self.importListings(self.listingsPath)
  File "F:\Elite\TD\plugins\eddblink_plug.py", line 649, in importListings
    supply_price, supply_units, supply_level, from_live))
UnboundLocalError: local variable 'from_live' referenced before assignment
```

**Comment by eyeonus** [comment]
Oops. Put the assignment in the wrong line.
