### ISSUE TITLE
No update of https://elite.tromador.com/ for the last days

### ISSUE THREAD

**Issue by Zafford** [eyeonus/Trade-Dangerous#187]
It seems that there has been no update of https://elite.tromador.com/ since the 7th of December. Not sure if this is the right place to submit that.

**Comment by Tromador** [comment]
I've restarted the server. 

The logfile said:
```
Please wait for all processes to report they are finished, in case they are currently active.
Busy signal acknowledged, getting live listings for export.
Exporting 'listings-live.csv'. (Got listings in 3 days, 6:20:47.297696)
Exception in thread Thread-4 (export_live):
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/elite/tradedangerous/./tradedangerous_listener.py", line 1026, in export_live
Listener reporting shutdown.
    for result in cursor:
                  ^^^^^^
  File "/home/elite/tradedangerous/./tradedangerous_listener.py", line 950, in fetchIter
    results = cursor.fetchmany(arraysize)
              ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'fetchmany'
```

**Comment by Tromador** [comment]
Hopefully @eyeonus can make something of that.

**Comment by Zafford** [comment]
But it seems to have still fixed the problem, so "case closed" ?

**Comment by eyeonus** [comment]
Testing the fix now, sorry for the delay.

**Comment by eyeonus** [comment]
Fixed in the latest update to the listener, pushed just now.

**Comment by Tromador** [comment]
Server updated.
