### ISSUE TITLE
Sell multiple commodities gives error

### ISSUE THREAD

**Issue by MarkAusten** [eyeonus/Trade-Dangerous#26]
Command line:
`trade.py sell --near="Orang/Bessel Gateway" --ly=100 --pad=L --limit=42 -vv "Advanced Medicines, Basic Medicines"`

Error report:
`Traceback (most recent call last):`
`  File "C:\Development\tradedangerous\trade.py", line 107, in <module>`
`    main(sys.argv)`
`  File "C:\Development\tradedangerous\trade.py", line 80, in main`
`    results = cmdenv.run(tdb)`
`  File "C:\Development\tradedangerous\commands\commandenv.py", line 81, in run`
`    return self._cmd.run(results, self, tdb)`
`  File "C:\Development\tradedangerous\commands\sell_cmd.py", line 78, in run`
`    item = tdb.lookupItem(cmdenv.item)`
`  File "C:\Development\tradedangerous\tradedb.py", line 1932, in lookupItem`
`    val=lambda kvTup: kvTup[1]`
`  File "C:\Development\tradedangerous\tradedb.py", line 2109, in listSearch`
`    "Error: '%s' doesn't match any %s" % (lookup, listType)`
`LookupError: Error: 'Advanced Medicines, Basic Medicines' doesn't match any Item`

Using the sell query with a single item works correctly.

**Comment by eyeonus** [comment]
It's not a bug. 'sell' was never intended to work with multiple items.

**Comment by eyeonus** [comment]
https://github.com/eyeonus/Trade-Dangerous/wiki/Command-Line-Options#sell-sub-command
