### ISSUE TITLE
Database doesn't complete updating: Category.csv not found

### ISSUE THREAD

**Issue by aadler** [eyeonus/Trade-Dangerous#31]
I wanted to update TD after a long absence, so I pulled from the github repository and ran `-O clean` but got an error that Category.csv was missing. Just in case, I deleted the entire TD directory, cloned it afresh, and still got the following error. Any suggestions?

```
E:\Elite\TD>trade import -P eddblink
NOTE: Rebuilding cache file: this may take a few moments.
NOTE: Missing "E:\Elite\TD\data\TradeDangerous.prices" file - no price data.
NOTE: Downloading file 'modules.json'.
NOTE: Requesting http://elite.ripz.org/files/modules.json
NOTE: Downloaded 297.8KB of gziped data   2.5MB/s
NOTE: Processing Upgrades: Start time = 2018-12-30 20:45:29.579455
NOTE: Finished processing Upgrades. End time = 2018-12-30 20:45:29.588431
NOTE: Downloading file 'index.json'.
NOTE: Requesting https://raw.githubusercontent.com/EDCD/coriolis-data/master/dist/index.json
NOTE: Downloaded   0.7MB of gziped data  19.5MB/s
NOTE: Processing Ships: Start time = 2018-12-30 20:45:29.875662
NOTE: Finished processing Ships. End time = 2018-12-30 20:45:29.887630
NOTE: Downloading file 'systems_populated.jsonl'.
NOTE: Requesting http://elite.ripz.org/files/systems_populated.jsonl
NOTE: Downloaded  20.5MB of gziped data   6.3MB/s
NOTE: Processing Systems: Start time = 2018-12-30 20:45:33.659592
NOTE: Finished processing Systems. End time = 2018-12-30 20:45:35.524649
NOTE: Downloading file 'stations.jsonl'.
NOTE: Requesting http://elite.ripz.org/files/stations.jsonl
NOTE: Downloaded 115.0MB of gziped data  15.7MB/s
NOTE: Processing Stations, this may take a bit: Start time = 2018-12-30 20:45:43.387194
NOTE: Simultaneously processing ShipVendors.
NOTE: Simultaneously processing UpgradeVendors, this will take quite a while.
NOTE: Finished processing Stations. End time = 2018-12-30 20:52:48.068146
NOTE: Downloading file 'commodities.json'.
NOTE: Requesting http://elite.ripz.org/files/commodities.json
NOTE: Downloaded 100.6KB of gziped data  98.5MB/s
NOTE: Processing Categories and Items: Start time = 2018-12-30 20:52:48.563327
NOTE: Checking for missing items....
Traceback (most recent call last):
  File "E:\Elite\TD\trade.py", line 107, in <module>
    main(sys.argv)
  File "E:\Elite\TD\trade.py", line 80, in main
    results = cmdenv.run(tdb)
  File "E:\Elite\TD\commands\commandenv.py", line 81, in run
    return self._cmd.run(results, self, tdb)
  File "E:\Elite\TD\commands\import_cmd.py", line 124, in run
    if not plugin.run():
  File "E:\Elite\TD\plugins\eddblink_plug.py", line 921, in run
    self.importCommodities()
  File "E:\Elite\TD\plugins\eddblink_plug.py", line 518, in importCommodities
    with open(str(tdb.dataPath / Path("Category.csv")), "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Elite\\TD\\data\\Category.csv'
```

**Comment by eyeonus** [comment]
I may have accidentally broken 'clean'. Looking into it now.

**Comment by eyeonus** [comment]
'clean' run completed without error.

**Comment by aadler** [comment]
Confirming that it is fixed; thanks!!
