### ISSUE TITLE
Bug with olddata

### ISSUE THREAD

**Issue by Lucaspec72** [eyeonus/Trade-Dangerous#94]
i just started using TD so it may not be a bug, but it looks like a bug.
i've tried running the command `trade olddata`, but when i did, i got this :

`Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lucas\AppData\Roaming\Python\Python39\Scripts\trade.exe\__main__.py", line 7, in <module>
  File "C:\Users\Lucas\AppData\Roaming\Python\Python39\site-packages\tradedangerous\trade.py", line 43, in main
    cli.main(sys.argv)
  File "C:\Users\Lucas\AppData\Roaming\Python\Python39\site-packages\tradedangerous\cli.py", line 70, in main
    trade(argv)
  File "C:\Users\Lucas\AppData\Roaming\Python\Python39\site-packages\tradedangerous\cli.py", line 125, in trade
    results = cmdenv.run(tdb)
  File "C:\Users\Lucas\AppData\Roaming\Python\Python39\site-packages\tradedangerous\commands\commandenv.py", line 83, in run
    return self._cmd.run(results, self, tdb)
  File "C:\Users\Lucas\AppData\Roaming\Python\Python39\site-packages\tradedangerous\commands\olddata_cmd.py", line 175, in run
    if not odyseey or row.station.checkOdyssey(odyssey):
NameError: name 'odyseey' is not defined`

looking at the error i'm pretty sure there's a typo somewhere in the code where odyssey is written odyseey.

**Comment by eyeonus** [comment]
No, you're right, that's a bug caused by a typo. At least it's an easy fix.
